import type { Metadata } from "next";
import "./globals.css";
import { YMapLoader } from './YMapLoader';

export const metadata: Metadata = {
  title: "Сестринское дело в косметологии",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
        </body>
    </html>
  );
}
