import logo from "./imgs/logo.png"
import plus from "./imgs/plus-svgrepo-com.svg"
import BenefitImg from "./imgs/BenefitImg.jpg"
import answers_firstImg from "./imgs/answers-firstImg.png"
import answers_secImg from "./imgs/answers-secImg.png"
import answers_thirdImg from "./imgs/answers-thirdImg.png"
import answers_fourImg from "./imgs/answers-fourImg.png"
import bonus_fiImg from "./imgs/bonus-fiImg.png"
import bonus_seImg from "./imgs/bonus-seImg.png"
import bonus_thImg from "./imgs/bonus-thImg.png"
import bonus_foImg from "./imgs/bonus-foImg.png"
import VK_logo from "./imgs/vk-logo.svg"
import footer_btns from "./imgs/footer-btns.png"

export { logo, plus, BenefitImg, answers_firstImg, answers_secImg, answers_thirdImg, answers_fourImg, bonus_fiImg, bonus_seImg, bonus_thImg, bonus_foImg, VK_logo, footer_btns }